// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RequestsManager.Infrastructure.Persistence;

#nullable disable

namespace RequestsManager.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261001181231_PrioritySortIndex")]
    partial class PrioritySortIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RequestsManager.Domain.Entities.RequestStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("NewStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("PreviousStatus")
                        .HasColumnType("tinyint");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestId", "ChangedAt")
                        .IsDescending(false, true);

                    b.ToTable("RequestStatusHistory", (string)null);
                });

            modelBuilder.Entity("RequestsManager.Domain.Entities.ServiceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("Priority")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SearchText")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(401)
                        .HasColumnType("nvarchar(401)")
                        .HasComputedColumnSql("UPPER([Title] + N' ' + [OrganizationName]) COLLATE Latin1_General_100_BIN2", false);

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Requests_CreatedAt");

                    b.HasIndex("OrganizationName")
                        .HasDatabaseName("IX_Requests_OrganizationName");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("OrganizationName"), new[] { "Status" });

                    b.HasIndex("SearchText")
                        .HasDatabaseName("IX_Requests_SearchText");

                    b.HasIndex("AssignedTo", "Status")
                        .HasDatabaseName("IX_Requests_AssignedTo_Status");

                    b.HasIndex("Priority", "CreatedAt")
                        .HasDatabaseName("IX_Requests_Priority_CreatedAt");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_Requests_Status_CreatedAt");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Status", "CreatedAt"), new[] { "Priority" });

                    b.ToTable("Requests", (string)null);
                });

            modelBuilder.Entity("RequestsManager.Domain.Entities.RequestStatusHistory", b =>
                {
                    b.HasOne("RequestsManager.Domain.Entities.ServiceRequest", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RequestsManager.Domain.Entities.ServiceRequest", b =>
                {
                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
